export const CREATE_TASK = 'createTask'
export const EDIT_TASK = 'editTask'
export const DELETE_TASK = 'deleteTask'
export const LIST_TASKS = 'listTasks'
export const SELECT_TASK = 'selectTask'
export const SET_ERROR = 'setError'